apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress
  namespace: app1
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - host: k8s-app1-app1ingr-a6f73ddafc-857828184.ap-south-1.elb.amazonaws.com
HTTP/1.1 404 Not Found
Server: awselb/2.0
Date: Fri, 18 Jul 2025 05:57:15 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Connection: keep-alive

      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app1-service
                port:
                  number: 80
