apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: app1
  labels:
    app: app1
spec:
  type: ClusterIP
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 3000  # or your actual container port
      protocol: TCP
